mubarak23/chainevents-contracts

- src/event.cairo
- src/event/event.cairo
- src/interfaces.cairo
- src/interfaces/IEvent.cairo
- src/lib.cairo
- PR for #4 
-  event contract where the storage variable and event that will be emitted from each function execution
> event storage and emitted event data structure

- .github/workflows/test_contract.yml
- Scarb.toml
- src/base/types.cairo
- src/event.cairo
- src/events.cairo
- src/events/events.cairo
- src/interfaces/IEvent.cairo
- src/lib.cairo
- tests/test_contract.cairo
> feat:add event and basic unit test for it

- tests/test_contract.cairo
Add test function in test_contract.cairo  for  testing  event_details  .
> task: #19 Event-details-function

- backend/.env.example
- backend/.gitignore
- backend/README.md
- backend/app.js
- backend/config/db.js
- backend/controllers/EventController.js
- backend/knexfile.js
- backend/middlewares/authorize.js
- backend/middlewares/validation.js
- backend/migrations/20241024140928_create_events_table.js
- backend/models/Event.js
- backend/package.json
- backend/routes/event.js
- backend/server.js
- backend/utils/auth.js
- backend/utils/response.js
- backend/utils/validator.js
- backend/validations/EventSchema.js
A backend folder was added to the main repo to handle backend interactivity.
A simple setup guide can be found on the README.md of the backend folder.
> Feature: added backend folder - expressjs backend

- src/events/events.cairo
- src/interfaces/IEvent.cairo
> chore:add upgradeable function

- src/events/events.cairo
- src/interfaces/IEvent.cairo
> add event registration count

- src/base/types.cairo
- src/events/eventnft.cairo
- src/events/events.cairo
- src/interfaces/IEvent.cairo
- src/interfaces/IEventNFT.cairo
> doc: add natspec comment to contracts

- src/events/events.cairo
- src/interfaces/IEvent.cairo
- tests/test_contract.cairo
> Feat: Unregister event

- src/events/eventnft.cairo
- src/interfaces/IEventNFT.cairo
> feat: add more function to eventNFT

- src/events/chainevents.cairo
> Small Public functions, Big Private Functions

- src/events/chainevents.cairo
> feat: private function for attendee's registered

- src/Docs/Read _Functions
Read Functions via the Voyager Explorer #88
>  Read Functions via the Voyager Explorer #88

- src/base/types.cairo
- src/events/chainevents.cairo
- src/interfaces/IEvent.cairo
- tests/test_contract.cairo
> feat: Fetch All Events

- src/events/feecollector.cairo
> feat: retrieve total event fees

- src/events/chainevents.cairo
- src/interfaces/IEvent.cairo
- tests/test_contract.cairo
> feat: implement function to fetch all atendees for a particular event

- src/events/chainevents.cairo
> create a private function for all events

- src/events/chainevents.cairo
> create private function for all attendees on events

- src/events/chainevents.cairo
> private function for event total amount paid

- src/base/types.cairo
- src/events/chainevents.cairo
- src/events/eventnft.cairo
- src/events/feecollector.cairo
- src/interfaces/IEvent.cairo
- src/interfaces/IPaymentToken.cairo
- src/mocks/mock_payment_token.cairo
- tests/test_contract.cairo
> fetch closed events

- src/events/chainevents.cairo
#137  Create a private function _fetch_all_paid_events and called in the public function fetch_all_paid_events
> feat:create a private function _fetch_all_paid_events

- src/events/chainevents.cairo
> abstract all closed event into a private function

- src/events/chainevents.cairo
> private ticket event counts

- src/base/errors.cairo
- src/base/types.cairo
- src/events/chainevents.cairo
- src/interfaces/IEvent.cairo
- tests/test_contract.cairo
> feat: Implement open event registration function

- src/events/chainevents.cairo
> chore: created a private function for fetch user paid event

- src/base/types.cairo
- src/events.cairo
- src/events/ticketverification.cairo
- src/interfaces/ITicketVerification.cairo
- tests/test_contract.cairo
Implemented the required functions. 
Added the required tests. 
Fixed a few path import errors. 
Updated some struct fields to pub to ensure visibility. 
Closes #151
> feat: create_ticket_event & mint_ticket

- src/events/ticketverification.cairo
- src/interfaces/ITicketVerification.cairo
- tests/test_contract.cairo
> add get ticket events details function 

- src/events/ticketverification.cairo
- src/interfaces/ITicketVerification.cairo
> Feat:setup internal private impl

- Scarb.toml
- src/base/types.cairo
- src/events/eventnft.cairo
- src/events/ticketeventaccount.cairo
- src/events/ticketeventnft.cairo
- src/interfaces.cairo
- src/interfaces/IEventNFT.cairo
- src/interfaces/ITicketEventAccount.cairo
- src/interfaces/ITicketEventNFT.cairo
> Ticket Event Account With TBA 

- src/base/errors.cairo
- src/group/groupsavings.cairo
- src/interfaces/IGroupSaving.cairo
- tests/test_group_savings_contract.cairo
> Feat: Implemented `start_cycle()` to begin ROSCA Contributions
